kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: a02-pvc-filesystem
  namespace: a02-ns  
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: slow  
  resources:
    requests:
      storage: 2Gi