apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: appnetwork
spec:
  podSelector:
    matchLabels:
      io.kompose.network/appnetwork: "true"
  ingress:
    - from:
        - podSelector:
            matchLabels:
              io.kompose.network/appnetwork: "true"