---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streaming
  volumes:
  - name: a02_pv
    persistentVolumeClaim:
      claimName: a02_pvc         
  template:
    metadata:
      labels:
        app: streaming
        io.kompose.network/appnetwork: "true"  # Add the network label
    spec:
      containers:
      - name: streaming
        image: avisoboleva/assig2:videostream
        volumeMounts:
          - mountPath: "/var/log/nginx"
            name: a02_pv         
        ports:
        - containerPort: 5003