---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload
  volumes:
  - name: a02_pv
    persistentVolumeClaim:
      claimName: a02_pvc         
  template:
    metadata:
      labels:
        app: upload
        io.kompose.network/appnetwork: "true"  # Add the network label 
    spec:
      containers:
      - name: upload
        image: avisoboleva/assig2:upload
        volumeMounts:
          - mountPath: "/app/video"
            name: a02_pv         
        ports:
        - containerPort: 5002