# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: upload-web-deployment
#   namespace: a02-ns 
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: upload
#   # volumes:
#   # - name: a02_pv
#   #   persistentVolumeClaim:
#   #     claimName: a02_pvc         
#   template:
#     metadata:
#       labels:
#         app: upload
#         io.kompose.network/appnetwork: "true"  # Add the network label 
#     spec:
#       containers:
#       - name: upload
#         image: avisoboleva/assig2:upload
#         # volumeMounts:
#         #   - mountPath: "/app/video"
#         #     name: a02_pv         
#         ports:
#         - containerPort: 5002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-web-deployment
  namespace: a02-ns 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload
  template:
    metadata:
      labels:
        app: upload
        io.kompose.network/appnetwork: "true"
    spec:
      containers:
      - name: upload
        image: avisoboleva/assig2:upload
        ports:
        - containerPort: 5002
        volumeMounts:
        - name: a02-upload
          mountPath: /app/videos
      volumes:
      - name: a02-upload
        persistentVolumeClaim:
          claimName: a02-pvc-upload