apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-web-deployment
  namespace: a02-ns 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload
  template:
    metadata:
      labels:
        app: upload
        io.kompose.network/appnetwork: "true"
    spec:
      containers:
      - name: upload
        image: avisoboleva/assig2:upload
        ports:
        - containerPort: 5002
        volumeMounts:
        - name: pv-upload-volume
          mountPath: /app/videos
      volumes:
      - name: pv-upload-volume
        persistentVolumeClaim:
          claimName: pvc-upload
