---
apiVersion: v1
kind: Service
metadata:
  name: upload-web
  namespace: a02-ns
spec:
  selector:
    app: upload
  ports:
  - protocol: TCP
    port: 5002
    targetPort: 5002
  type: LoadBalancer

