---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  volumes:
  - name: a02_pv
    persistentVolumeClaim:
      claimName: a02_pvc         
  template:
    metadata:
      labels:
        app: mysql
        io.kompose.network/appnetwork: "true"  # Add the network label
    spec:
      containers:
      - name: mysql
        image: avisoboleva/assig2:mysql
        volumeMounts:
          - mountPath: "/var/log/nginx"
            name: a02_pv         
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: video_db