---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filesystem-deployment
  namespace: a02-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filesystem         
  template:
    metadata:
      labels:
        app: filesystem
        io.kompose.network/appnetwork: "true"  # Add the network label
    spec:
      containers:
      - name: filesystem
        image: avisoboleva/assig2:filesys        
        ports:
        - containerPort: 5001
        volumeMounts:
        - name: pv-filesys-volume2
          mountPath: /app/uploads
      volumes:
      - name: pv-filesys-volume2
        persistentVolumeClaim:
          claimName: pvc-filesys
