---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filesystem-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filesystem
  volumes:
  - name: a02_pv
    persistentVolumeClaim:
      claimName: a02_pvc            
  template:
    metadata:
      labels:
        app: filesystem
        io.kompose.network/appnetwork: "true"  # Add the network label
    spec:
      containers:
      - name: filesystem
        image: avisoboleva/assig2:filesys
        volumeMounts:
          - mountPath: "/var/log/nginx"
            name: a02_pv         
        ports:
        - containerPort: 5001