---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filesystem-deployment
  namespace: a02-ns 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filesystem
  template:
    metadata:
      labels:
        app: filesystem
        io.kompose.network/appnetwork: "true"
    spec:
      containers:
      - name: filesystem
        image: avisoboleva/assig2:filesys
        ports:
        - containerPort: 5002
        volumeMounts:
        - name: a02-filesystem
          mountPath: /app/uploads
      volumes:
      - name: a02-filesystem
        persistentVolumeClaim:
          claimName: a02-pvc-filesystem      