---
apiVersion: v1
kind: Service
metadata:
  name: filesystem
  namespace: a02-ns  
spec:
  selector:
    app: filesystem
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
  type: LoadBalancer
  