---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-deployment
  namespace: a02-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication    
  template:
    metadata:
      labels:
        app: authentication
        io.kompose.network/appnetwork: "true"  # Add the network label
    spec:
      containers:
      - name: authentication
        image: avisoboleva/assig2:auth      
        ports:
        - containerPort: 5000


        