---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication
  volumes:
    - name: a02_pv
      persistentVolumeClaim:
        claimName: a02_pvc      
  template:
    metadata:
      labels:
        app: authentication
        io.kompose.network/appnetwork: "true"  # Add the network label
    spec:
      containers:
      - name: authentication
        image: avisoboleva/assig2:auth
        volumeMounts:
          - mountPath: "/var/log/nginx"
            name: a02_pv        
        ports:
        - containerPort: 5000


        